force-app/main/default/objects/Booking_Details__c/Booking_Details__c.object-meta.xml
<CustomObject>
    <description>This object Holds the booking details of the House DMO and Tentat  details and Rental Span for Rental Booking</description>
    <label>Booking Details</label>
    <nameField>
        <label>Booking Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Details__c/fields/House_Address__c.field-meta.xml
<CustomField>
    <fullName>House_Address__c</fullName>
    <label>House Address</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Booking_Details__c/fields/House_Number__c.field-meta.xml
<CustomField>
    <fullName>House_Number__c</fullName>
    <label>House Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Details__c/fields/Idle_Days__c.field-meta.xml
<CustomField>
    <fullName>Idle_Days__c</fullName>
    <formula>Rental_Start_Date__c - Tenant_Person__r.EmployeeJoiningDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Idle Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking_Details__c/fields/Istemporaryallocationneeded__c.field-meta.xml
<CustomField>
    <fullName>Istemporaryallocationneeded__c</fullName>
    <description>This forumla used to understand if the user requires a temporary accomodation</description>
    <formula>IF(
  AND(
    Rental_Start_Date__c - Tenant_Person__r.EmployeeJoiningDate__c &gt;= 1,
    Rental_Start_Date__c - Tenant_Person__r.EmployeeJoiningDate__c &lt;= 20
  ),
  TRUE,
  FALSE
)</formula>
    <inlineHelpText>This forumla used to understand if the user requires a temporary accomodation</inlineHelpText>
    <label>Is temporary allocation needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking_Details__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Details__c/fields/Rental_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rental_End_Date__c</fullName>
    <label>Rental End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking_Details__c/fields/Rental_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Rental_Start_Date__c</fullName>
    <label>Rental Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking_Details__c/fields/Tenant_Person__c.field-meta.xml
<CustomField>
    <fullName>Tenant_Person__c</fullName>
    <description>This field holds the employee who will be tenant of this house.</description>
    <inlineHelpText>This field holds the employee who will be tenant of this house.</inlineHelpText>
    <label>Tenant Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Booking Details</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gas_Service_Request__c/Gas_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Gas Service Request</label>
    <nameField>
        <displayFormat>GSR-{00000}</displayFormat>
        <label>Gas Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gas Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gas_Service_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Gas Service Requests</relationshipLabel>
    <relationshipName>Gas_Service_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gas_Service_Request__c/fields/Gas_Detail__c.field-meta.xml
<CustomField>
    <fullName>Gas_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gas Detail</label>
    <referenceTo>Gas_Detail__c</referenceTo>
    <relationshipLabel>Gas Service Requests</relationshipLabel>
    <relationshipName>Gas_Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gas_Service_Request__c/fields/Installation_Required__c.field-meta.xml
<CustomField>
    <fullName>Installation_Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Installation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gas_Service_Request__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Gas_Service_Request__c/fields/Service_Status__c.field-meta.xml
<CustomField>
    <fullName>Service_Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internet_Service_Request__c/Internet_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Internet Service Request</label>
    <nameField>
        <displayFormat>ISR-{00000}</displayFormat>
        <label>Internet Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internet Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Internet_Service_Request__c/fields/Connection_Type__c.field-meta.xml
<CustomField>
    <fullName>Connection_Type__c</fullName>
    <label>Connection Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internet_Service_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Internet Service Requests</relationshipLabel>
    <relationshipName>Internet_Service_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Internet_Service_Request__c/fields/Installation_Required__c.field-meta.xml
<CustomField>
    <fullName>Installation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Internet_Service_Request__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <label>Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Porter_Service_Request__c/Porter_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Porter Service Request</label>
    <nameField>
        <label>Porter Service Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porter Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Porter_Service_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Porter Service Requests</relationshipLabel>
    <relationshipName>Porter_Service_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Porter_Service_Request__c/fields/From_Address__c.field-meta.xml
<CustomField>
    <fullName>From_Address__c</fullName>
    <label>From Address</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Porter_Service_Request__c/fields/Move_Type__c.field-meta.xml
<CustomField>
    <fullName>Move_Type__c</fullName>
    <label>Move Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Household Move</fullName>
            </value>
            <value>
                <fullName>Full Pack &amp; Move</fullName>
            </value>
            <value>
                <fullName>Partial Move</fullName>
            </value>
            <value>
                <fullName>Long-Distance Move</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Porter_Service_Request__c/fields/Moving_Date__c.field-meta.xml
<CustomField>
    <fullName>Moving_Date__c</fullName>
    <label>Moving Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Porter_Service_Request__c/fields/Porter_Detail__c.field-meta.xml
<CustomField>
    <fullName>Porter_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Porter Detail</label>
    <referenceTo>Porter_Details__c</referenceTo>
    <relationshipLabel>Porter Service Requests</relationshipLabel>
    <relationshipName>Porter_Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Porter_Service_Request__c/fields/Service_Status__c.field-meta.xml
<CustomField>
    <fullName>Service_Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Porter_Service_Request__c/fields/To_Address__c.field-meta.xml
<CustomField>
    <fullName>To_Address__c</fullName>
    <label>To Address</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Porter_Service_Request__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mini Truck</fullName>
            </value>
            <value>
                <fullName>Tempo</fullName>
            </value>
            <value>
                <fullName>Lorry</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Temporary_Accommodation_Service__c/Temporary_Accommodation_Service__c.object-meta.xml
<CustomObject>
    <label>Temporary Accommodation Service</label>
    <nameField>
        <displayFormat>TAS-{00000}</displayFormat>
        <label>Temporary Accommodation Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temporary Accommodation Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Temporary_Accommodation_Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Temporary Accommodation Services</relationshipLabel>
    <relationshipName>Temporary_Accommodation_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Temporary_Accommodation_Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
                <default>true</default>
                <label>Booked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactRelatedRecordsController.cls
public with sharing class ContactRelatedRecordsController {
    @AuraEnabled(cacheable=true)
    public static Map<String, List<SObject>> getRelatedRecords(Id contactId) {
        Map<String, List<SObject>> result = new Map<String, List<SObject>>();
        
        // Query booking details
        List<Booking_Details__c> Booking_Details = [
            select Id,  Name, Rental_End_Date__c, House_Number__c, Rental_Start_Date__c, Payment_Frequency__c, createddate,House_Address__c, Tenant_Person__c, Istemporaryallocationneeded__c, Idle_Days__c from Booking_Details__c 
            WHERE Tenant_Person__c = :contactId order by createddate desc limit 1       
        ];
        result.put('bookingdetail', Booking_Details);
        

           // Query booking details
         List<Porter_Service_Request__c> Porter_Service = [
            select Id,  CreatedDate ,Move_Type__c, Notes__c, Scheduled_Date__c, Service_Status__c, Moving_Date__c, From_Address__c, Requested_Date__c, To_Address__c, Vehicle_Type__c, Contact__c, Porter_Detail__c from Porter_Service_Request__c
            WHERE Contact__c = :contactId order by createddate desc limit 1
        ];
        result.put('porterservice', Porter_Service);

                 // Query booking details
         List<Gas_Service_Request__c> Gas_Service = [
            select Id,  Name, Requested_Date__c, Connection_Type__c, Scheduled_Date__c, Service_Status__c, Notes__c, Installation_Required__c, Contact__c, Gas_Detail__c from Gas_Service_Request__c
            WHERE Contact__c = :contactId order by createddate desc limit 1
            
        ];
        result.put('gasservice', Gas_Service);

          // Query booking details
          List<Internet_Service_Request__c> Internet_Service = [
            select Id,  Name,Speed_Requirement__c, Scheduled_Date__c, Usage_Type__c, Installation_Required__c, Service_Status__c, Notes__c, Connection_Type__c, Requested_Date__c, Preferred_ISP__c, Contact__c, Internet_Detail__c from Internet_Service_Request__c
            WHERE Contact__c = :contactId order by createddate desc limit 1
        ];
        result.put('internetservice', Internet_Service);

             // Query booking details
             List<Temporary_Accommodation_Service__c> Temporary_Accommodation_Service = [
                select Id,  Name,  Accommodation_Address__c, Check_In__c, Check_out__c, Duration_of_Stay__c, Number_of_Guests__c, Contact__c, Temporary_Accommodation_Detail__c,Temporary_Accommodation_Detail__r.Accommodation_Name__c,Temporary_Accommodation_Detail__r.Type__c, Status__c  from Temporary_Accommodation_Service__c 
                WHERE Contact__c = :contactId order by createddate desc limit 1            
            ];
            result.put('tempservice', Temporary_Accommodation_Service);


        

        
        return result;
    }

    @AuraEnabled(cacheable=true)
    public static Id getContactIdForCurrentUser() {
        // Query the User record for the current user and return the ContactId
        return [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1].ContactId;
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String, String> getRelatedContentRecords(Id contactId) {
        Map<String, String> result = new Map<String, String>();
        
        // Query booking details
        List<Booking_Details__c> Booking_Details = [
            select Id,  Name, Rental_End_Date__c, House_Number__c, Rental_Start_Date__c, Payment_Frequency__c, createddate,House_Address__c, Tenant_Person__c, Istemporaryallocationneeded__c, Idle_Days__c from Booking_Details__c 
            WHERE Tenant_Person__c = :contactId order by createddate desc limit 1
               
        ];
        
        if(Booking_Details.size() > 0){
            Id contentId = [select id,ContentDocumentId from ContentDocumentLink where LinkedEntityId =: Booking_Details[0].Id].ContentDocumentId;
            string link = '\"'+URL.getOrgDomainURL().toExternalForm() + '/sfc/servlet.shepherd/document/download/' + contentId+'\"';
            result.put('rentalAgreement', link);
        }
        return result;
    }
    
     @AuraEnabled
    public static Map<String, List<SObject>> getRelatedRecordsImperative(Id contactId) {
        Map<String, List<SObject>> result = new Map<String, List<SObject>>();
        
        // Query booking details
        List<Booking_Details__c> Booking_Details = [
            select Id,  Name, Rental_End_Date__c, House_Number__c, Rental_Start_Date__c, Payment_Frequency__c, createddate,House_Address__c, Tenant_Person__c, Istemporaryallocationneeded__c, Idle_Days__c from Booking_Details__c 
            WHERE Tenant_Person__c = :contactId order by createddate desc limit 1
              
        ];
        result.put('bookingdetail', Booking_Details);
        

           // Query booking details
         List<Porter_Service_Request__c> Porter_Service = [
            select Id,  CreatedDate ,Move_Type__c, Notes__c, Scheduled_Date__c, Service_Status__c, Moving_Date__c, From_Address__c, Requested_Date__c, To_Address__c, Vehicle_Type__c, Contact__c, Porter_Detail__c from Porter_Service_Request__c
            WHERE Contact__c = :contactId order by createddate desc limit 1
           
        ];
        result.put('porterservice', Porter_Service);

                 // Query booking details
         List<Gas_Service_Request__c> Gas_Service = [
            select Id,  Name, Requested_Date__c, Connection_Type__c, Scheduled_Date__c, Service_Status__c, Notes__c, Installation_Required__c, Contact__c, Gas_Detail__c from Gas_Service_Request__c
            WHERE Contact__c = :contactId order by createddate desc limit 1
            
        ];
        result.put('gasservice', Gas_Service);

          // Query booking details
          List<Internet_Service_Request__c> Internet_Service = [
            select Id,  Name,Speed_Requirement__c, Scheduled_Date__c, Usage_Type__c, Installation_Required__c, Service_Status__c, Notes__c, Connection_Type__c, Requested_Date__c, Preferred_ISP__c, Contact__c, Internet_Detail__c from Internet_Service_Request__c
            WHERE Contact__c = :contactId order by createddate desc limit 1
             
        ];
        result.put('internetservice', Internet_Service);

             // Query booking details
             List<Temporary_Accommodation_Service__c> Temporary_Accommodation_Service = [
                select Id,  Name,  Accommodation_Address__c, Check_In__c, Check_out__c, Duration_of_Stay__c, Number_of_Guests__c, Contact__c, Temporary_Accommodation_Detail__c,Temporary_Accommodation_Detail__r.Accommodation_Name__c,Temporary_Accommodation_Detail__r.Type__c, Status__c  from Temporary_Accommodation_Service__c 
                WHERE Contact__c = :contactId order by createddate desc limit 1
                
            ];
            result.put('tempservice', Temporary_Accommodation_Service);


        

        
        return result;
    }

    @AuraEnabled
    public static Map<String, String> getRelatedContentRecordsImperative(Id contactId) {
        Map<String, String> result = new Map<String, String>();
        
        // Query booking details
        List<Booking_Details__c> Booking_Details = [
            select Id,  Name, Rental_End_Date__c, House_Number__c, Rental_Start_Date__c, Payment_Frequency__c, createddate,House_Address__c, Tenant_Person__c, Istemporaryallocationneeded__c, Idle_Days__c from Booking_Details__c 
            WHERE Tenant_Person__c = :contactId order by createddate desc limit 1
              
        ];
        
        if(Booking_Details.size() > 0){
            Id contentId = [select id,ContentDocumentId from ContentDocumentLink where LinkedEntityId =: Booking_Details[0].Id].ContentDocumentId;
            string link = '\"'+URL.getOrgDomainURL().toExternalForm() + '/sfc/servlet.shepherd/document/download/' + contentId+'\"';
            result.put('rentalAgreement', link);
        }
        return result;
    }
}